# Generated by Django 2.2.7 on 2019-12-11 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20191211_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.School'),
        ),
    ]
