# Generated by Django 2.2.7 on 2019-12-11 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_teacher_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='dded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
