# Generated by Django 2.2.7 on 2019-12-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_teacher_dded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='dded',
            new_name='added',
        ),
    ]
