# Generated by Django 2.2.7 on 2019-12-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20191211_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='document_upload',
            field=models.ImageField(blank=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='document_upload',
            field=models.ImageField(blank=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='feecollector',
            name='document_upload',
            field=models.ImageField(blank=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to='documents'),
        ),
    ]
