# Generated by Django 2.2.7 on 2019-12-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20191212_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
