# Generated by Django 2.2.7 on 2019-12-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_pbsuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbsuser',
            name='picture',
            field=models.ImageField(blank=True, default='static/assets/images/users/avatar-1.jpg', null=True, upload_to='profiles'),
        ),
    ]
