# Generated by Django 2.2.7 on 2019-12-14 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_diesel'),
    ]

    operations = [
        migrations.AddField(
            model_name='diesel',
            name='diesel_rate',
            field=models.IntegerField(default=74, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
