# Generated by Django 2.2.7 on 2019-12-14 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_diesel_diesel_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='diesel',
            name='total',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
